spring:
  application.name: spring-ai-demo
  ai:
    openai:
      api-key: ${SPRING_AI_DEMO_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
      audio:
        speech:
          options:
            model: gpt-4o-mini-tts
            voice: onyx
            response-format: wav
            speed: 0.95
    vectorstore:
      qdrant:
        host: localhost
        port: 6334          # gRPC port
        collection-name: vector_store
        initialize-schema: true
        use-tls: false